sudo: required  
dist: trusty  
language: node_js  
node_js:  
   - node # will use latest node

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:  
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

before_script: # commands to run before the build step
   - npm install -g --silent @angular/cli
   - npm install -g --silent greenkeeper-lockfile@1
   - npm install -g --silent firebase-tools 
   - npm install

script: # the build step
   - ng test --watch false
   - ng build --prod

after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && firebase deploy --token $FIREBASE_TOKEN --non-interactive

notifications:
  email: # only receive email when the build status changes (someone broke the build!) 
    on_failure: change
    on_success: change   
